### ISSUE TITLE
Unable to import template

### ISSUE THREAD

**Issue by OsipovDV** [Unam1024/TemplateOSLinux-plus#1]
Hi!
I'm trying to import your template to my zabbix server and get following error:

Cannot find graph "Disk space usage {#FSNAME} - history" used in screen "System performance - plus".

**Comment by Unam1024** [comment]
Graph prototype linked to parent template is not included in the export file. That is removed from this template for now, as I cannot find suitable idea to deal with it. Sorry for late reply and your inconvenience.

**Comment by OsipovDV** [comment]
ok, thanks. I solve this issue same manner.
